name         'msimonin-cassandra'
version      '0.7.3'
author       'Jochen Schalanda,Matthieu Simonin'
license      'Apache 2.0'
project_page 'https://github.com/msimonin/puppet-cassandra'
source       'https://github.com/msimonin/puppet-cassandra'
summary      'Puppet module to install Apache Cassandra from the DataStax distribution. Forked from gini/cassandra'
description  'A Puppet module to install the DataStax Community edition using the official repositories. Forked from gini/cassandra.'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/apt', '1.x'
